node {

    def buildNumber = env.BUILD_NUMBER
    def branch = "job13"
    currentBuild.displayName = "QA1 $branch $buildNumber" 
    currentBuild.description = "descr@2017-02-06-17:23:12"

    stage 'initializes'

    ws('/tmp/shared') {
    // some block


        ws('/tmp/shared/repo_apps') {
            stage 'checkout repo_apps'
            
            checkout changelog: false, poll: false, scm: [$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '955df68f-6268-408a-8aa9-dcc50b2d84c0', url: 'git@github.com:escoem/pipeline-tests.git']]]



   stage 'build QA'
   def jobValue = "job13"

   stage 'update repos on target QA1 environment'

   sshagent(credentials: ['955df68f-6268-408a-8aa9-dcc50b2d84c0'], ignoreMissing: true) {
      stage 'installx apps search head'

   stage 'restart search head 2'

   stage 'install index apps'
             
   stage 'show bundle status'

   stage 'apply bundles index'

   stage 'show bundle status'

   }


       stage 'run python test kit'
       def jobValue2 = "job13"

        stage 'load qa2 pipeline'
        load 'two-pipes/Jenkinsfile.QA2'

   }
 }

}()
